//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voca.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noun
    {
        public int Id { get; set; }
        public string Nominative { get; set; }
        public string Genitive { get; set; }
        public string Dative { get; set; }
        public string Accusative { get; set; }
        public string Vocative { get; set; }
        public string Instrumental { get; set; }
        public string Locative { get; set; }
        public bool IsGuaranteed { get; set; }
    }
}
